language: python
python: 3.6

matrix:
  include:
    - python: 2.7
    - python: 3.7
      sudo: required
      dist: xenial
    - python: 3.6
    - python: 3.5
    - python: 3.4

script:
- python --version
- python2 --version
- python3 --version
- python2.7 --version || true
- python3.7 --version || true
- python3.6 --version || true
- python3.5 --version || true
