name: Release
on:
  push:

jobs:
  windows:
    name: ${{ matrix.python }} / ${{ matrix.os }}
    strategy:
      matrix:
        os: [Windows]
        python:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - run: python -c "from pathlib import Path; (Path.cwd() / ('a'*131) / ('a'*131)).mkdir(parents=True)"
