on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/setup-python@v4
        with:
           python-version: "3.7"
      - run: python -c "import ssl; print( ssl.OPENSSL_VERSION )"
      - run: python -c "import ssl; print( ssl.create_default_context() )"
