on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v4
        with:
           python-version: "3.7"
      - run: python -c "import ssl; print( ssl.OPENSSL_VERSION )"
      - run: python -c "import ssl; print( ssl.get_default_verify_paths() )"
