on:
  push:

jobs:
  stb:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/setup-python@v2
      - run: pip install https://github.com/pradyunsg/sphinx-theme-builder/archive/refs/heads/main.zip
      - run: pip install --no-deps --no-build-isolation https://github.com/pradyunsg/furo/archive/refs/heads/main.zip
